### ISSUE TITLE
Feature Request | Backup Folders

### ISSUE THREAD

**Issue by MirayXS** [Koupah/Among-Us-Editor#10]
# Feature Request | Backup Folders

#### When applying changes, it would be useful to make a folder named " backup " with the old files that were edited.

**Comment by MirayXS** [comment]
I would use this feature as i use the fortegreen color alongside the invisible name settings when i like it, and i make backups of my files.

**Comment by MirayXS** [comment]
it would be handy if there are other folders inside the backup folder so that the backups dont get overwritten

**Comment by dada513** [comment]
Why not just use commit history ?

**Comment by Koupah** [comment]
> I would use this feature as i use the fortegreen color alongside the invisible name settings when i like it, and i make backups of my files.

Why do you not just change your settings back AFTER you're done? Like opening the editor back up, turning off invisible name (you also need to retype a username after turning off invisible name) and set your color to something else?

**Comment by dada513** [comment]
Oh my bad, I thought this was about the repo’s files, have a nice day

**Comment by MirayXS** [comment]
> Why do you not just change your settings back AFTER you're done? Like opening the editor back up, turning off invisible name (you also need to retype a username after turning off invisible name) and set your color to something else?

I have the fear that the conseguences of the fortegreen color would still be applied.

**Comment by Koupah** [comment]
It won't, once you change color using the editor to something that isn't Fortegreen, everything will go back to normal. I promise you. However, your 'issue' has given me the idea of adding Profiles, that way you can quickly swap between your config settings. Is that something you'd like to see?

**Comment by MirayXS** [comment]
yes! that's a cool feature to add

**Comment by Koupah** [comment]
Alright, I'll take a shot at it. If you join the discord, I'll give you a contributor role. https://discord.com/invite/HTm3mwK

**Comment by MirayXS** [comment]
sure 👍
