### ISSUE TITLE
Full value list

### ISSUE THREAD

**Issue by camas** [Koupah/Among-Us-Editor#13]
|Index|Name used by Among Us|Type|Comment|
|--|--|--|--|
|0|lastPlayerName|String||
|1|touchConfig|int||
|2|colorConfig|uint||
|3|ignored unknown||Default `1`|
|4|ignored sendName|bool|Default `False`|
|5|ignored sendTelemetry|bool|Default `False`|
|6|ignored sendDataScreen|bool|Default `False`|
|7|showAdsScreen|bit flags|Personalized `0x00`, NonPersonalized `0x01`, Accepted `0x80`, Purchased `0x82`|
|8|showMinPlayerWarning|bool||
|9|showOnlineHelp|bool||
|10|lastHat|uint||
|11|sfxVolume|byte||
|12|musicVolume|byte||
|13|joyStickSize|float||
|14|lastGameStart|long|Ticks since last game started. Used to check if left game too early|
|15|lastSkin|uint||
|16|lastPet|uint||
|17|censorChat|bool||
|18|lastLanguage|uint||
|19|vsync|bool||

as of v2020.9.22

Types are .NET types

**Comment by Koupah** [comment]
Thank you for this, I just updated the README to add this. 
Very much appreciated
