### ISSUE TITLE
My playerPrefs does not work...

### ISSUE THREAD

**Issue by SokroKalimi** [Koupah/Among-Us-Editor#15]
Is there any way I can fix this? It may be because it's from mobile...

**Comment by Vresod** [comment]
Can you provide more details please?

**Comment by Koupah** [comment]
> Is there any way I can fix this? It may be because it's from mobile...

Could you tell me what isn't working?
Are you creating the file on PC then running it on mobile?
What error messages are showing?

**Comment by SokroKalimi** [comment]
I can't open it. Is there a way I can open it with the among us file editor. Is there a place I should open it?

**Comment by Koupah** [comment]
Please join the discord for support, your reply doesn't make enough sense for me to offer a solution.

My main guess is you don't know how to download or run the editor, 
On the right hand side of the main page for this github repository, press releases then scroll down and click on the .jar file to download it.

If you already downloaded it, download java from https://java.com/download and install it then right click the Among-Us-Editor.jar file and press Open With Java

**Comment by Koupah** [comment]
Closing this as it's been 2 days without a response.
Not sure if I helped them in discord or not, but 90% chance they just didn't have Java installed.
