### ISSUE TITLE
Among-Us-Editor-1.51.jar wont open

### ISSUE THREAD

**Issue by Shadowmind-Developer** [Koupah/Among-Us-Editor#17]
I think its some kind of bug or sth.
I tried to open your .jar file, then a console is starting and then after a short time it closes. I have the newest version of Java Installed on my Computer. Also the launcher cannot start it. :C 

Maybe it helps you when i make a screenshot of that window, so here it is:

![image](https://user-images.githubusercontent.com/62246232/97800699-ae6ba000-1c37-11eb-8dbd-15a8b7fe94d3.png)

The problem is: it closes so fast. but i catched it.

**Comment by Shadowmind-Developer** [comment]
PS: in the console window it say something is wrong with the main class or it couldnt find it.

**Comment by Koupah** [comment]
This is an issue a couple people had, the only **reliable** workaround I have found is wrapper the jar to an exe. 
If you join the discord server I can provide an .exe copy of the editor for you, I've already had it tested with only 2 out of 42 users having an issue.

I don't know how to properly fix it, for one person when I refactored the project and it worked and for others it did nothing.

Do you have Java 8 or something newer?

**Comment by Shadowmind-Developer** [comment]
I have the newest Java version. PS: i already joined your discord :D
