### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by Idk111111** [Koupah/Among-Us-Editor#19]
What if I dont want to use the editor when I play  and I have already installed  the among us editor. What do I do  so that I can use play without the editor even if it is  in my system and also because of some reason after i installed the editor I am not able to use the sabotage button and also after using the editor I am not getting enough public games to play.

**Comment by Koupah** [comment]
This isn't the editors fault, you must've installed something else.

The editor doesn't "install", just try reinstalling your game.

If you have something like AmongUsPlus (Which isn't safe to use), then remove it.
