### ISSUE TITLE
Error: Could not find or load main class C:\Users\---\Desktop\Among-Us-Editor-1.51.jar

### ISSUE THREAD

**Issue by codingMASTER398** [Koupah/Among-Us-Editor#22]
### I don't know whats happening here.

I have the latest java version installed as well as the Among us editor. I open it with the launcher and it says
>_**"Error: Could not find or load main class C:\Users\---\Desktop\Among-Us-Editor-1.51.jar"**_

Is there something else i have to download? What should i do?

**Comment by Koupah** [comment]
A lot of people have had random java issues. If you join the discord you can download a newer version that has some of these fixed and there's even an exe version made with Launch4J that seems to solve a lot of issues people had.

Other than that, nothing I can really do
