### ISSUE TITLE
Customize keyboard keys

### ISSUE THREAD

**Issue by Donokami** [Koupah/Among-Us-Editor#23]
Hey, thanks for your work.
Would it be possible to add the feature of editing the keyboards keys, to set another keys to move, kill or do tasks?

**Comment by Vresod** [comment]
No, as that would require modifying the game's executable or other binary files, which in addition to being a monumental task, the method that you use to do this would have to change every update.

unless theres a file you can change for the keys.

**Comment by GingerGigiCat** [comment]
That is impossible without mods, AUE is not a mod.

**Comment by Koupah** [comment]
Sorry but as stated above, this can't be done inside of Among Us Editor.
You could always remap your keyboard keys depending on what keyboard brand you have or even using a scripting language such as AutoHotKey.

Incase you didn't know though, Q can be used for killing and E (and spacebar I believe?) can be used to open the sabotage menu, enter vents and open tasks.
