### ISSUE TITLE
New Twitch Pet

### ISSUE THREAD

**Issue by EliTheCoder** [Koupah/Among-Us-Editor#29]
The current version of the program doesn't have support for the Twitch pet pictured below.
![image](https://user-images.githubusercontent.com/4386738/102300809-3b826400-3f1b-11eb-828d-11d4c3f6f131.png)

**Comment by Koupah** [comment]
Was this closed because you realised it does? The lastest 'release' doesn't but if you join the discord you can download a prerelease version!
