### ISSUE TITLE
Skeld.net's IP has changed

### ISSUE THREAD

**Issue by Slymeball** [Koupah/Among-Us-Editor#30]
Hey, I'm back! Anyways, I just tried to log into Skeld.net using the AUEditor and it kicked me for not being on the right server. They switched up the server IP to **192.241.154.115**. This should hopefully be a quick fix.

**Comment by Koupah** [comment]
Hello & Welcome back!

I was contacted by the Skeld.net owner a little bit back, I had completely forgotten to update it.
Thanks for bringing this to my attention and yes, you were right, it is a quick fix. Already been complete!
