### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by AFellowSpeedrunner** [Koupah/Among-Us-Editor#37]
I want to have a addition where you can disable quick chat.

**Comment by Vresod** [comment]
can you explain what exactly "quick chat" is?

**Comment by AFellowSpeedrunner** [comment]
Well @Vresod, It is a new feature in the new Among Us update. Under 18's get quickchat and over 18's have the option to enable and disable at will. For some unknown reason mine is stuck as no quickchat. I thought you could have that as a new feature where you can disable and enable it from inside the program. I hope you can add it btw love your program it is amazing!!!

**Comment by AFellowSpeedrunner** [comment]
Also don't know almost anything about javascript soooo yeah I can't do that.

**Comment by Vresod** [comment]
i'll see what i can do

**Comment by AFellowSpeedrunner** [comment]
Noice

**Comment by Koupah** [comment]
I'll check it out later on and see what I can do!

**Comment by Koupah** [comment]
Added in latest commits!
Compile it yourself or wait for the release I'll put out in the next 24h.
