### ISSUE TITLE
task bar updates are 100% a checked checkbox

### ISSUE THREAD

**Issue by jellytoaster** [Koupah/Among-Us-Editor#38]
read title

**Comment by Vresod** [comment]
can you elaborate?

**Comment by Koupah** [comment]
> read title

Are you saying that Among Us Editor always sets task bar updates to be on? Or are you saying you want a setting for it?
Please explain further so I can understand.

**Comment by Koupah** [comment]
I accidentally pressed "Close with comment" smh

**Comment by Koupah** [comment]
I'm closing this as you've given no response. 
In the future I will add a task bar updates setting incase that is the reason you opened this issue.
