### ISSUE TITLE
error update detection

### ISSUE THREAD

**Issue by x0rld** [Koupah/Among-Us-Editor#42]
![image](https://user-images.githubusercontent.com/45242856/112871373-7fab0600-90bf-11eb-8588-8581d2bec8b3.png)
the last release of the software is the 1.6, it looks like  detect the pre release as release
![image](https://user-images.githubusercontent.com/45242856/112871463-93ef0300-90bf-11eb-8ff0-e9df3df2e582.png)

**Comment by Koupah** [comment]
I purposely made it show 1.611 as the latest release so that users could get the bug fixed version and latest cosmetics.

It's not a full release because I barely added anything, and still don't know what to add currently in order to convince myself to make a proper release.
