### ISSUE TITLE
Quick Chat

### ISSUE THREAD

**Issue by Metwie** [Koupah/Among-Us-Editor#44]
I have the NullContinuanceToken error in Among Us So i tried the Option "All chat", but nothing change. What do i have to do?

**Comment by Koupah** [comment]
Honestly, the new update seemed to have account issue and this is probably related to that, I'd just say wait it out and I'll reply to this again if I work it out.

**Comment by Guii0** [comment]
Same problem

**Comment by Koupah** [comment]
Still unaware of what causes this. Going to close the issue as it doesn't appear to be related to AUE.
