### ISSUE TITLE
Skeld.net region error

### ISSUE THREAD

**Issue by bjm2007** [Koupah/Among-Us-Editor#47]
The region of skeld.net doesn't work in among us and it shows that it's a region of North America.

**Comment by Koupah** [comment]
I've already fixed it, just haven't released it. I was waiting for any other issues to arise first so I don't release 2 versions in 1 week.
I will release it in the next 24 hours, currently preoccupied with something.

If you know how to, I encourage you to compile it yourself or you can join the discord where I already sent a jar file of the version with it fixed!
