### ISSUE TITLE
Changing chat options doesnt work

### ISSUE THREAD

**Issue by Marquessmark11** [Koupah/Among-Us-Editor#50]
So in among us I entered my age wrong and now im stuck with only the quick chat feature, so in this tool I changed it and nothing

**Comment by Koupah** [comment]
I think Among Us is just forcing it back to quick chat because of the age. Technically changing chat option does work, you just need to go into your playerPrefs and change your age.

**Comment by Koupah** [comment]
In the future, I'll probably add the ability to change your age.

**Comment by Imlxgit** [comment]
this doesnt work either
