### ISSUE TITLE
Unix System (Mac + Linux) compatibility has still not been added yet.

### ISSUE THREAD

**Issue by Slymeball** [Koupah/Among-Us-Editor#6]
Problem: The program looks for a Java component that does not exist.

Error Message:
> Your system doesn't seem to want to work! Are you on Windows?
> [The Microsoft Windows Look and Feel - com.sun.java.swing.plaf.windows.WindowsLookAndFeel] not supported on this platform

**Comment by Koupah** [comment]
![image](https://user-images.githubusercontent.com/25888315/93897961-07d9d880-fd36-11ea-905f-fcf84f0fad25.png)
As far as I know, Among Us isn't even on Mac is it? And that message clearly states you should be on Windows

**Comment by rirze** [comment]
...A major selling point of Java is that it's cross-os-compatible. Personallh, I prefer to run Among Us on my Steam with Linux. 

Why is this locked to Windows? It certainly isn't because of Java.

**Comment by Slymeball** [comment]
> ![image](https://user-images.githubusercontent.com/25888315/93897961-07d9d880-fd36-11ea-905f-fcf84f0fad25.png)
> As far as I know, Among Us isn't even on Mac is it? And that message clearly states you should be on Windows

[ProtonDB](https://www.protondb.com/app/945360) rates Among Us with a Gold rating.
You can run it on GNU systems, just with a small hoop and a few hiccups in animations.

Sorry if I came off as aggressive, I just wanted to remind.

> Why is this locked to Windows? It certainly isn't because of Java.

The program requests from a Windows component (is this the right terminology?), the theme.
Since neither MacOS or GNU use Windows themes, it comes up with an error. That's all I could get from the .jar.
**Take this with a grain of salt,** since I'm clearly not a Java programmer.

I'll go ahead and close the issue, since this clearly was a mistake on my part. Thanks for your understanding.

## **THREAD CLOSED.**

**Comment by Koupah** [comment]
This was not your fault, it was mine. I did state Windows only but that's because I didn't know you could play on Linux. The reason it's force set to use the Windows look and feel is because I prefer it over the default Java one but honestly I can fix it up. I'll also require someone to inform me of the player prefs directory or I could just add a File Chooser if your OS is Linux. Im writing this on my phone about to go to bed (AEST Timezone) so I'll probably get to work on this tomorrow. For now im reopening the issue. Thank you for bringing this to my attention!

**Comment by Koupah** [comment]
> Problem: The program looks for a Java component that does not exist.
> 
> Error Message:
> 
> > Your system doesn't seem to want to work! Are you on Windows?
> > [The Microsoft Windows Look and Feel - com.sun.java.swing.plaf.windows.WindowsLookAndFeel] not supported on this platform



> ...A major selling point of Java is that it's cross-os-compatible. Personally, I prefer to run Among Us on my Steam with Linux.
> 
> Why is this locked to Windows? It certainly isn't because of Java.

This was fixed as of Version 1.25.
Thank you for bringing this to my attention, once again I have zero clue it was playable on non-windows/mobile platforms like Linux and possibly even mac.
