### ISSUE TITLE
File Finder cannot see hidden folders.

### ISSUE THREAD

**Issue by Slymeball** [Koupah/Among-Us-Editor#7]
Folders starting with . (hidden folders in Linux) cannot be found using the file explorer.
This is especially problematic, since the default Steam folder is found in .steam.

Using the file name field, you can open these, so it's not one of the most important things to fix.

I don't know if this could be a simple fix or not.

**Comment by Koupah** [comment]
Thank you so much for bringing this to my attention!

It should be fixed with the next update within the next 6 hours.

**Comment by Koupah** [comment]
Fixed this in version 1.35!
Thanks again for bring this to my attention.
